env = Environment()

env['APP_TARGET'] = 'Joint2DApp'
env['APP_SOURCES'] = ['Joint2DApp.cpp']
env['DEBUG'] = 0

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')
