env = Environment()

env['APP_TARGET'] = 'BasicBox2DApp'
env['APP_SOURCES'] = ['BasicBox2DApp.cpp']
env['DEBUG'] = 0

env = SConscript('../../../scons/SConscript', exports = 'env')

SConscript('../../../../../scons/SConscript', exports = 'env')

